# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 040f05b7841f19dd39d906f0fb4e2771ad1dae5d5484e68fd9df07341ce69209cde63c954d38976fbbcad81d536489c63d46379a10505ce492c06ba561ce50b0

test:
  secret_key_base: 5cd6f830121f47d5abd0223807fa6847b26b8ea517ac165ea5d1fd6941642fe553b788dbbc5c09af00d8601d30a017a7a72cf8492f8fdc81aed986d0ed3ca38c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 23807fa6847b26b8ea517ac165ea5d1fd6941642fe553b788dbbc5c09af00d8601d30a017ac81aed986d0ed3ca38c5cd6f830121f47d5abd027a72cf8492f8fd #<%= ENV["SECRET_KEY_BASE"] %>
